# Generated by Django 4.1.6 on 2023-02-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=16)),
                ('to_number', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
            },
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['from_number'], name='api_callrec_from_nu_9ba7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['to_number'], name='api_callrec_to_numb_fbd6a7_idx'),
        ),
    ]
